version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: employee-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  admin:
    build: ./admin-panel
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  hr:
    build: ./hr-panel
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

