version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  employee-entry:
    build: ./employee-entry
    container_name: employee-entry
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql

  admin-panel:
    build: ./admin-panel
    container_name: admin-panel
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  hr-panel:
    build: ./hr-panel
    container_name: hr-panel
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql-data:

